---
- name: Add GPG key
  command: sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add Elasticsearch Repository
  copy: 
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/

- name: Update Cache
  dnf: 
    update_cache: yes

- name: Install Elasticsearch
  dnf: 
    name: elasticsearch
    state: present

- name: Configure Elasticsearch change cluster name
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "cluster.name: demo-elk"
    state: present

- name: Configure Elasticsearch give cluster descriptive name
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "node.name: elk-1"
    state: present

- name: Configure Elasticsearch Add network.host
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: 0.0.0.0"
    state: present

- name: Configure Elasticsearch Add http.port
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "http.port: 9200"
    state: present

- name: Configure Elasticsearch Add discovery.type
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "discovery.type: single-node"
    state: present

- name: Creating an empty file for startup-timeout conf 1 of 2
  file:
    path: "/etc/systemd/system/elasticsearch.service.d"
    state: directory

- name: Creating an empty file for startup-timeout conf 2 of 2
  file:
    path: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    state: touch

- name: Prevent systemd service start operation from timing out
  copy:
    dest: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    content: |
      [Service]
      TimeoutStartSec=3min

- name: Run daemon-reload for elasticsearch
  systemd: daemon_reload=yes

- name: Enable service Elasticsearch and ensure it is not masked
  systemd: 
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running 
  systemd: state=started name=elasticsearch
  
- name: Install Kibana
  dnf: 
    name: kibana
    state: present

- name: Configure Kibana Add server.port
  lineinfile: 
    dest: /etc/kibana/kibana.yml
    line: "server.port: 5601"
    state: present

- name: Configure Kibana Add server.host
  lineinfile:  
    dest: /etc/kibana/kibana.yml
    line: 'server.host: "0.0.0.0"'
    state: present

- name: Configure Kibana Add server.name
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'server.name: "demo-kibana"'
    state: present

- name: Configure Kibana Add elasticsearch.hosts
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'elasticsearch.hosts: ["http://0.0.0.0:9200"]'
    state: present

- name: Run daemon-reload for kibana
  systemd: daemon-reload=yes

- name: Enable service Kibana
  systemd:
    name: kibana
    enabled: yes

- name: Start Elasticsearch & Kibana
  shell: systemctl start elasticsearch && systemctl start kibana

- name: Install Logstash
  dnf: 
    name: logstash
    state: present

- name: Run daemon-reload for logstash
  systemd: daemon_reload=yes

- name: Enable service logstash
  systemd:
    name: logstash
    enabled: yes

- name: Ensure logstash is running
  systemd: state=started name=logstash

- name: Install Filebeat
  dnf: 
    name: filebeat
    state: present
# tasks file for ELK
